### ISSUE TITLE
Vendor Simlin

### ISSUE THREAD

**Issue by gsverhoeven** [jandraor/readsdr#6]
Hi there! 

Thanks for creating this package. I just managed to use the Open source SD GUI Simlin (https://simlin.com/)  to fully specify a model from Jim Duggan's book, export it as XMILE code, import in R using readsdr and simulate it using deSolve! 

I needed to manually edit the XMILE file to make it work: I had to replace Vendor Simlin with Ventana.

Can you add Simlin as a vendor, and maybe also allow for files from any other vendor?

Kind regards,
Gertjan

**Comment by jandraor** [comment]
I'll have a look.

**Comment by jandraor** [comment]
Hi Gertjan,

It is not straightforward to add vendors, given that there is no uniformity in applying XMILE guidelines. So far, **readsdr** has been tailored to Vensim & Stella's idiosyncrasies. I ran a quick test on Simlin & found the issue you mentioned [here](https://github.com/bpowers/simlin/issues/82). However, if everything is lowercase, it works (download the latest development version). For now, I'm treating Simlin as if it were a file from Stella.

**Comment by gsverhoeven** [comment]
Hi Jair, great, thanks a lot. 

What about treating all unknown vendors as Stella, maybe while throwing a warning that the vendor is unknown and weird stuff might happen? I searched the Simlin repo for "vendor" and came across this model where vendor is "SDlabs", so it seems there are more vendors out there (not very familiar with SD modeling yet).

https://github.com/bpowers/simlin/blob/c8506c93ffb043411856a8533aa470f7816047bf/public/population.xmile
